In [6]:
import pandas as pd
import numpy as np

In [7]:
df1=pd.read_csv("C:\\Users\\Hello\\Desktop\\Dataset\\social.csv")

In [8]:
df1

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [9]:
df1.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [10]:
df1.drop("User ID",axis=1,inplace=True)

In [11]:
df1

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [12]:
df1=df1.drop("Gender",axis=1)

In [13]:
df1

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [14]:
X=df1[["Age","EstimatedSalary"]]

In [15]:
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [16]:
y=df1[["Purchased"]]

In [17]:
y

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [18]:
##splitting of data

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.20)

In [21]:
Xtrain.shape

(320, 2)

In [22]:
Xtest.shape

(80, 2)

In [23]:
ytrain.shape

(320, 1)

In [24]:
ytest.shape

(80, 1)

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
logreg=LogisticRegression()

In [27]:
logreg

LogisticRegression()

In [28]:
logreg.fit(Xtrain,ytrain)

E:\python\MSSQL15.MSSQLSERVER\anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [29]:
logreg.score(Xtest,ytest)

0.65

In [30]:
logreg.score(Xtrain,ytrain)

0.640625

In [31]:
##Xtrain,Xtest,Yrain,Ytest
Standard Scalar

SyntaxError: invalid syntax (Temp/ipykernel_3348/950139735.py, line 2)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [32]:
sc.fit(Xtrain)

NameError: name 'sc' is not defined

In [ ]:
Xtrain.sample()

In [ ]:
sc.mean_

In [33]:
Xtrain_sc=sc.transform(Xtrain)

NameError: name 'sc' is not defined

In [34]:
Xtest_sc=sc.transform(Xtest)

NameError: name 'sc' is not defined

In [35]:
Xtest_sc

NameError: name 'Xtest_sc' is not defined

In [36]:
from sklearn.linear_model import LogisticRegression

In [37]:
ajlog=LogisticRegression()

In [38]:
ajlog


LogisticRegression()

In [39]:
ajlog.fit(Xtrain_sc,ytrain)

NameError: name 'Xtrain_sc' is not defined

In [40]:
ajlog.score(Xtest_sc,ytest)

NameError: name 'Xtest_sc' is not defined

In [41]:
##Normalization

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
norm=MinMaxScaler()

In [44]:
norm.fit(Xtrain)

MinMaxScaler()

In [45]:
norm.transform(Xtrain)

array([[0.23809524, 0.32592593],
       [0.71428571, 0.14814815],
       [0.78571429, 0.97037037],
       [0.80952381, 0.04444444],
       [0.21428571, 0.51111111],
       [0.97619048, 0.85185185],
       [0.69047619, 0.68148148],
       [0.5       , 0.2       ],
       [0.07142857, 0.00740741],
       [0.38095238, 0.42222222],
       [0.14285714, 0.02962963],
       [0.45238095, 0.34814815],
       [0.61904762, 0.91851852],
       [0.73809524, 0.54814815],
       [0.80952381, 0.91111111],
       [0.16666667, 0.55555556],
       [0.92857143, 0.33333333],
       [0.14285714, 0.05925926],
       [0.54761905, 0.22222222],
       [0.0952381 , 0.35555556],
       [0.4047619 , 0.54074074],
       [0.4047619 , 0.34074074],
       [0.42857143, 0.76296296],
       [0.04761905, 0.4962963 ],
       [0.21428571, 0.03703704],
       [0.42857143, 0.82222222],
       [0.57142857, 0.48148148],
       [0.4047619 , 0.17037037],
       [0.30952381, 0.39259259],
       [0.54761905, 0.47407407],
       [0.

In [46]:
norm.transform(Xtest)

array([[0.38095238, 0.71851852],
       [0.83333333, 0.4962963 ],
       [0.28571429, 0.01481481],
       [0.26190476, 0.98518519],
       [0.66666667, 0.12592593],
       [0.28571429, 0.53333333],
       [0.78571429, 0.05925926],
       [0.83333333, 0.94814815],
       [0.4047619 , 0.42962963],
       [0.80952381, 1.        ],
       [0.5       , 0.6       ],
       [0.35714286, 0.4       ],
       [0.95238095, 0.63703704],
       [0.97619048, 0.1037037 ],
       [0.4047619 , 0.21481481],
       [0.26190476, 0.20740741],
       [0.4047619 , 0.17777778],
       [0.23809524, 0.54814815],
       [0.5       , 0.41481481],
       [0.4047619 , 0.31851852],
       [0.02380952, 0.08148148],
       [0.19047619, 0.        ],
       [0.54761905, 0.48148148],
       [0.73809524, 0.37037037],
       [0.47619048, 0.25925926],
       [0.04761905, 0.43703704],
       [0.23809524, 0.8       ],
       [0.33333333, 0.02222222],
       [0.64285714, 0.22222222],
       [0.21428571, 0.55555556],
       [0.

In [62]:
from sklearn.linear_model import LinearRegression

In [63]:
lreg=LinearRegression()

In [64]:
lreg.fit(Xtrain,ytrain)

LinearRegression()

In [65]:
lreg.score(Xtest,ytest)

0.5110578130922332

In [66]:
Xtrain.head()

Age  EstimatedSalary
101   28            59000
389   48            35000
245   51           146000
283   52            21000
6     27            84000

In [67]:
lreg.predict([[52,21000]])

array([[0.55490235]])

In [68]:
lreg.predict([[48,35000]])

array([[0.50070923]])

In [70]:
from sklearn.svm import SVC


In [71]:
svm=SVC()

In [72]:
svm.fit(Xtrain,ytrain)

E:\python\MSSQL15.MSSQLSERVER\anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [73]:
svm.score(Xtest,ytest)

0.8

In [74]:
from sklearn.linear_model import LogisticRegression

In [76]:
logreg=LogisticRegression()

In [77]:
logreg.fit(Xtrain,ytrain)

E:\python\MSSQL15.MSSQLSERVER\anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [78]:
logreg.score(Xtest,ytest)

0.65

In [79]:
from sklearn.preprocessing import StandardScaler

In [81]:
ss=StandardScaler()

In [82]:
ss.fit(Xtrain)

StandardScaler()

In [83]:
Xtrain_ss=ss.transform(Xtrain)

In [84]:
Xtest=ss.transform(Xtest)

In [85]:
from sklearn.linear_model import LogisticRegression

In [87]:
logreg1=LogisticRegression()

In [88]:
logreg1.fit(Xtrain_ss,ytrain)

E:\python\MSSQL15.MSSQLSERVER\anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()