In [4]:
import pandas as pd
import numpy as np

In [6]:
X=np.arange(2,10,2)

In [7]:
X

array([2, 4, 6, 8])

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [10]:
poly=PolynomialFeatures()

In [14]:
df1=pd.DataFrame(df1)

In [15]:
df1

0
0  2
1  4
2  6
3  8

In [16]:
poly.fit(df1)

PolynomialFeatures()

In [17]:
dfpoly=poly.transform(df1)

In [18]:
dfpoly

array([[ 1.,  2.,  4.],
       [ 1.,  4., 16.],
       [ 1.,  6., 36.],
       [ 1.,  8., 64.]])

In [19]:
df1

0
0  2
1  4
2  6
3  8

In [20]:
poly3=PolynomialFeatures(degree=3)

In [21]:
poly3.fit(df1)

PolynomialFeatures(degree=3)

In [22]:
dfpoly3=poly3.transform(df1)

In [23]:
dfpoly3


array([[  1.,   2.,   4.,   8.],
       [  1.,   4.,  16.,  64.],
       [  1.,   6.,  36., 216.],
       [  1.,   8.,  64., 512.]])