In [1]:
import pandas as pd
import numpy as np

In [2]:
ary1=np.arange(10,100,10)

In [3]:
ary1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
train_test_split(ary1,test_size=0.20)

[array([50, 70, 10, 20, 60, 80, 90]), array([40, 30])]

In [6]:
from sklearn.model_selection import KFold

In [7]:
kf=KFold()

In [8]:
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [9]:
objkf=kf.split(ary1)

In [10]:
objkf

<generator object _BaseKFold.split at 0x00000141169FA970>

In [11]:
list(objkf)

[(array([2, 3, 4, 5, 6, 7, 8]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7, 8]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7, 8]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5, 8]), array([6, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8]))]

In [12]:
list(objkf)

[]

In [13]:
objkf1=kf.split(ary1)

In [14]:
objkf1

<generator object _BaseKFold.split at 0x00000141169FAEB0>

In [15]:
for x,y in objkf1:
    print(x)
    print(y)

[2 3 4 5 6 7 8]
[0 1]
[0 1 4 5 6 7 8]
[2 3]
[0 1 2 3 6 7 8]
[4 5]
[0 1 2 3 4 5 8]
[6 7]
[0 1 2 3 4 5 6 7]
[8]
